server:
  port: 8002
 
mybatis:
  type-aliases-package: com.hufu.springcloud.entity          # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/*.xml                       # mapper映射文件
 
spring:
  profiles: test  #开发环境
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/test_1              # 数据库名称
    username: root
    password: password
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
            hibernate.format_sql: true
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
 
eureka:
  client:
    service-url:
         defaultZone: http://localhost:7001/eureka   #将客户端注册进eureka服务列表内
        #defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
  instance:
    instance-id: ${spring.cloud.client.ipAddress}-hystrix:${server.port}   #自定义服务名称信息  启动多个服务做集群需要设置为不同的ID值
    prefer-ip-address: true   #访问路径可以显示IP地址
    leaseRenewalIntervalInSeconds: 10          #剔除不健康节点。
    leaseExpirationDurationInSeconds: 30       #剔除不健康节点。
