server:
  port: 8600
eureka:
  client:
    service-url:
      #注册服务到eureka上，记住这里要加上eureka-server的用户名和密码
      defaultZone: http://root:hulongfu@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    #可能比较长，复制的时候请写在一行
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    appname: springcloud-config-server
